### ISSUE TITLE
Ship phase fails

### ISSUE THREAD

**Issue by wagnerand** [mozilla-extensions/xpi-manifest#176]
```
2022-05-30 09:00:00,067 - asyncio - DEBUG - Using selector: EpollSelector
2022-05-30 09:00:00,081 - github3 - INFO - Building a url from ('https://api.github.com', 'repos', 'mozilla-extensions', 'firefox-translations')
2022-05-30 09:00:00,081 - github3 - INFO - Missed the cache building the url
2022-05-30 09:00:00,081 - github3 - DEBUG - GET https://api.github.com/repos/mozilla-extensions/firefox-translations with {}
2022-05-30 09:00:00,083 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.github.com:443
2022-05-30 09:00:00,301 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla-extensions/firefox-translations HTTP/1.1" 200 None
2022-05-30 09:00:00,303 - github3 - INFO - JSON was returned
2022-05-30 09:00:00,305 - github3 - INFO - Building a url from ('https://api.github.com/repos/mozilla-extensions/firefox-translations', 'releases', 'tags', '1.1.2')
2022-05-30 09:00:00,306 - github3 - INFO - Missed the cache building the url
2022-05-30 09:00:00,306 - github3 - DEBUG - GET https://api.github.com/repos/mozilla-extensions/firefox-translations/releases/tags/1.1.2 with {}
2022-05-30 09:00:00,441 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "GET /repos/mozilla-extensions/firefox-translations/releases/tags/1.1.2 HTTP/1.1" 404 None
2022-05-30 09:00:00,442 - githubscript.github - INFO - Release firefox-translations-1.1.2-build1 does not exist. Creating it...
2022-05-30 09:00:00,443 - github3 - INFO - Building a url from ('https://api.github.com/repos/mozilla-extensions/firefox-translations', 'releases')
2022-05-30 09:00:00,443 - github3 - INFO - Missed the cache building the url
2022-05-30 09:00:00,444 - github3 - DEBUG - POST https://api.github.com/repos/mozilla-extensions/firefox-translations/releases with {"tag_name": "1.1.2", "target_commitish": "f376f50d7e2616e433f64f39055f9ab708e5af46", "name": "firefox-translations-1.1.2-build1", "draft": false, "prerelease": false}, {}
2022-05-30 09:00:00,567 - urllib3.connectionpool - DEBUG - https://api.github.com:443 "POST /repos/mozilla-extensions/firefox-translations/releases HTTP/1.1" 404 None
Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/githubscript/github.py", line 26, in release
    existing_release = await _get_release_from_tag(github_repository, git_tag)
  File "/app/lib/python3.9/site-packages/scriptworker_client/utils.py", line 467, in wrapped
    return await retry_async(
  File "/app/lib/python3.9/site-packages/scriptworker_client/utils.py", line 407, in retry_async
    return await func(*args, **kwargs)
  File "/app/lib/python3.9/site-packages/githubscript/github.py", line 65, in _get_release_from_tag
    return await async_release_from_tag(git_tag)
  File "/app/lib/python3.9/site-packages/scriptworker_client/utils.py", line 494, in run
    return await loop.run_in_executor(executor, pfunc)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/lib/python3.9/site-packages/github3/repos/repo.py", line 2559, in release_from_tag
    json = self._json(self._get(url), 200)
  File "/app/lib/python3.9/site-packages/github3/models.py", line 161, in _json
    raise exceptions.error_for(response)
github3.exceptions.NotFoundError: 404 Not Found
```

https://firefox-ci-tc.services.mozilla.com/tasks/Nv361J8RTfqLDSlpGc01ag/runs/0/logs/public/logs/live_backing.log

**Comment by escapewindow** [comment]
We haven't granted the releng bots write access to the firefox-translations repo: https://github.com/mozilla-extensions/firefox-translations/settings/access

https://github.com/orgs/mozilla-extensions/teams/bots/members

**Comment by escapewindow** [comment]
Granted bots access, crafted special release phase graph: [green](https://firefox-ci-tc.services.mozilla.com/tasks/aijMPnGtS4aAfA71CqjbeQ)

https://github.com/mozilla-extensions/firefox-translations/releases/tag/1.1.2

**Comment by wagnerand** [comment]
Aha, thanks! I suppose we need that for every repo that wants to use the github tagging feature. Is that part of the documentation already? If not, we probably want to add it, I wasn't aware of this requirement.

**Comment by escapewindow** [comment]
+1, I added it to #177 at least: https://github.com/mozilla-extensions/xpi-manifest/blob/main/manifests/template-example.yml.template#L37-L40
